# Generated by Django 4.2 on 2023-05-07 18:43

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("accounts", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="customuser",
            name="faculty",
            field=models.CharField(blank=True, max_length=1000),
        ),
        migrations.AddField(
            model_name="customuser",
            name="position",
            field=models.CharField(blank=True, max_length=1000),
        ),
    ]
